ヘッダーとヒーローの作成
into2008/frontend-basic-site pull request #1
Opened 2024-11-12 16:41 UTC by into2008

2024-11-18 07:17 UTC, toma0705 requested changes
2点だけ修正をお願いします

2024-11-18 07:17 UTC, toma0705 commented on index.html
> +                   <span class="hero-main-copy-accent"> "GRAND"</span>  <br>
```suggestion
                   <span class="hero-main-copy-accent"> “GRAND”</span>  <br>
```
""を“”に変えてください

2024-11-18 07:17 UTC, toma0705 commented on style.css
> +  background-image: url(./img/hero.png);
背景画像の見えている部分がfigmaと少し異なります。ギターも見えるようにしてほしいです
ヒントはbackground-positionです

2024-11-21 02:02 UTC, toma0705 commented
一次レビューOKです！

2024-11-23 02:05 UTC, renyagi commented
approve

2024-12-08 14:03 UTC, merged